### ISSUE TITLE
HTTP Quickstart is currently broken as the paths are out of date

### ISSUE THREAD

**Issue by leggetter** [tigrisdata/tigris-docs#316]
https://www.tigrisdata.com/docs/quickstarts/quickstart-http/

**Comment by TheLazyIndianTechie** [comment]
Yup, I can confirm this is still an issue. Was wondering what I was doing wrong.

**Comment by ovaistariq** [comment]
Unfortunately, we haven't been able to update it yet. I will get this prioritized. In the meantime could you take a look at the API reference and see if that works for you: https://www.tigrisdata.com/docs/references/api/

**Comment by TheLazyIndianTechie** [comment]
> Unfortunately, we haven't been able to update it yet. I will get this prioritized. In the meantime could you take a look at the API reference and see if that works for you: https://www.tigrisdata.com/docs/references/api/

Thank you.

**Comment by ibrahim-akrab** [comment]
I will give this a look and make sure the quickstart follows the paths in the API reference.

**Comment by ovaistariq** [comment]
@ibrahim-akrab thank you for the contribution, I have added a few comments on the PR. Once those are addressed, I would be happy to merge this.

**Comment by TheLazyIndianTechie** [comment]
Thanks @ibrahim-akrab and @ovaistariq . 

This now works but until the point where you have to fetch auth token  

```
curl -X POST https://api.preview.tigrisdata.cloud/v1/auth/token \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data grant_type=client_credentials \
  --data client_id=your_client_id_here \
  --data client_secret=your_client_secret_here
```

I keep getting an error regardless of anything I try:
```
{"error":{"code":"UNAUTHENTICATED","message":"Invalid credentials"}}
```

I have tried recreating the project, double-checked errors. Maybe I'm missing something or doing something wrong?

**Comment by ibrahim-akrab** [comment]
@TheLazyIndianTechie I've reported that problem too. I think it's got something to do with the creation process from the cli.
Until there's a fix for it, you can create the key from the web interface then continue with the quickstart

**Comment by TheLazyIndianTechie** [comment]
> @TheLazyIndianTechie I've reported that problem too. I think it's got something to do with the creation process from the cli. Until there's a fix for it, you can create the key from the web interface then continue with the quickstart

Yeah I'm having the same issue from web as well. Not sure what the issue is. I read your message on the other PR so tried web.

**Comment by ovaistariq** [comment]
The quickstart has been fixed to address the issue you were seeing: https://www.tigrisdata.com/docs/quickstarts/quickstart-http/

Basically, this is how the curl command to fetch token needs to be:
```
curl -X POST https://{your_tigris_uri}/v1/auth/token \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data grant_type=client_credentials \
  --data-urlencode client_id=your_client_id_here \
  --data-urlencode client_secret=your_client_secret_here
```
