### ISSUE TITLE
Python Vector search client example results in TypeError

### ISSUE THREAD

**Issue by NotJoeMartinez** [tigrisdata/tigris-docs#413]
**Describe the bug**
When following the steps on the python vector search [Getting Started](https://www.tigrisdata.com/docs/concepts/vector-search/python/) page. [Step 3](https://www.tigrisdata.com/docs/concepts/vector-search/python/#3-create-the-vector-database-client) attempts to show the user how to build a client using the following code:
```python
from tigrisdb.client import TigrisClient
from tigrisdb.types import ClientConfig

client = TigrisClient(
            config=ClientConfig(
              server_url=<region uri here>,
              project_name="vectordemo",
              client_id=<client id here>,
              client_secret=<client secret here>
        )).get_search()
```

However this will result in the following traceback:
```
Traceback (most recent call last):
  File "path/to/client_test.py", line 19, in <module>
    config=ClientConfig(
           ^^^^^^^^^^^^^
TypeError: ClientConfig.__init__() got an unexpected keyword argument 'project_name'
```
### This is a caused by two issues: 
1.  The [ClientConfig](https://github.com/tigrisdata/tigris-client-python/blob/667d484dd4c6159a7e55a6e70c8a5cf3a23c3971/tigrisdb/types/__init__.py#LL11C5-L11C12) object is expecting the variable `project` not `project_name` as specified in the docs.
2. The [TigrisClient](https://github.com/tigrisdata/tigris-client-python/blob/667d484dd4c6159a7e55a6e70c8a5cf3a23c3971/tigrisdb/client.py#LL23C1-L23C70) is expecting a `conf` argument not `config` as specified in the docs

My **proposed solution** would be to change the [step three](https://www.tigrisdata.com/docs/concepts/vector-search/python/#3-create-the-vector-database-client) snippet to:
```python
from tigrisdb.client import TigrisClient
from tigrisdb.types import ClientConfig

client = TigrisClient(
            conf=ClientConfig(
              server_url=<region uri here>,
              project="vectordemo",
              client_id=<client id here>,
              client_secret=<client secret here>
        )).get_search()
```

**To Reproduce**
1. Create a new tigris project from the dashboard 
2. Install `tigrisdb` python module via pip 
3. Attempt to create a `TigrisClient` as seen on [step 3](https://www.tigrisdata.com/docs/concepts/vector-search/python/#3-create-the-vector-database-client) 

Ex: 
```python
from tigrisdb.client import TigrisClient
from tigrisdb.types import ClientConfig

client = TigrisClient(
            config=ClientConfig(
              server_url=<region uri here>,
              project_name="vectordemo",
              client_id=<client id here>,
              client_secret=<client secret here>
        )).get_search()
print(type(client)) 
```

**Expected behavior**
To successfully build a client object using the example code in the docs

**Desktop (please complete the following information):**
- MacOS Ventura Version 13.2 
- Python 3.11.3

**Comment by NotJoeMartinez** [comment]
Made PR with proposed changes  #414

**Comment by ovaistariq** [comment]
Thanks for reporting and fixing it. The PR has been merged.
